# Generated by Django 5.0.6 on 2024-06-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_alter_game_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessuser',
            name='blitz_rating',
        ),
        migrations.RemoveField(
            model_name='chessuser',
            name='classic_rating',
        ),
        migrations.RemoveField(
            model_name='chessuser',
            name='rapid_rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1200, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('degree_of_confidence', models.FloatField(default=100)),
                ('chess_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.chessuser')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.gametype')),
            ],
        ),
    ]
