# Generated by Django 5.0.6 on 2024-05-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_won', models.BooleanField()),
                ('number_of_leads', models.IntegerField()),
                ('accuracy_white', models.FloatField(null=True)),
                ('accuracy_black', models.FloatField(null=True)),
                ('player_black', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_black', to='chess_app.chessplayer')),
                ('player_white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_white', to='chess_app.chessplayer')),
            ],
        ),
    ]
