# Generated by Django 5.0.6 on 2024-06-09 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chess_app', '0002_delete_chessgame_delete_chessplayer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('result', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameSearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time', models.IntegerField(null=True)),
                ('time_per_move', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FideTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('short_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blitz_rating', models.FloatField(null=True)),
                ('rapid_rating', models.FloatField(null=True)),
                ('classic_rating', models.FloatField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fide_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chess_app.fidetitle')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('game_notation', models.TextField(null=True)),
                ('white_rating', models.FloatField(null=True)),
                ('black_rating', models.FloatField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('chess_user_black', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chess_user_black', to='chess_app.chessuser')),
                ('chess_user_white', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chess_user_white', to='chess_app.chessuser')),
                ('game_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.gameresult')),
                ('game_search_settings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chess_app.gamesearchsettings')),
            ],
        ),
        migrations.AddField(
            model_name='gamesearchsettings',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.gametype'),
        ),
    ]
