# Generated by Django 5.0.6 on 2024-06-18 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_notation',
            new_name='pgn_file',
        ),
        migrations.CreateModel(
            name='MoveUCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('is_white', models.BooleanField()),
                ('uci', models.CharField(max_length=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.game')),
            ],
        ),
    ]
