# Generated by Django 5.0.6 on 2024-06-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0005_alter_game_game_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
