# Generated by Django 5.0.6 on 2024-06-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0007_remove_chessuser_blitz_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('chess_user', 'game_type')},
        ),
    ]
