# Generated by Django 5.0.6 on 2024-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0008_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveuci',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='moveuci',
            name='time_on_clock',
            field=models.FloatField(null=True),
        ),
    ]
