# Generated by Django 5.0.6 on 2024-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0009_moveuci_last_update_moveuci_time_on_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveuci',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
